using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using YeahGames.DAO;

namespace YeahGames
{
    /// <summary>
    /// Lógica interna para Listar.xaml
    /// </summary>
    public partial class Listar : Window
    {
        JogoDao dao;
        public Listar()
        {
            InitializeComponent();
            dao = new JogoDao();
            dgListar.ItemsSource = dao.listar();

        }

        private void DgListar_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgListar.Columns[0].Width = 70;
            dgListar.Columns[0].Header = "Código";
            dgListar.Columns[1].Width = 150;
            dgListar.Columns[2].Width = 100;
            dgListar.Columns[3].Width = 100;
        }
    }
}
